const quotes = [
    {quote: "Read a thousand books, and your words will flow like a river", author: "- Lisa See"},
    {quote: "I try to create sympathy for my characters, then turn the monsters loose.", author: "- Stephen King"},
    {quote: "Prose is architecture, not interior decoration.", author: "- Ernest Hemingway"},
    {quote: "It’s none of their business that you have to learn to write. Let them think you were born that way.", author: "- Ernest Hemingway"},
    {quote: "Most writers regard the truth as their most valuable possession, and therefore are most economical in its use.", author: "- Mark Twain"},
    {quote: "To produce a mighty book, you must choose a mighty theme.", author: "- Herman Melville"},
    {quote: "All that we are is the result of what we have thought.", author: "- Buddha"},
    {quote: "I have no special talent. I am only passionately curious.", author: "- Albert Einstein"},
    {quote: "If you judge people, you have no time to love them.", author: "- Mother Teresa"},
    {quote: "Wisely, and slow. They stumble that run fast.", author: "- William Shakespeare"},
    {quote: "The most courageous act is still to think for yourself. Aloud.", author: "- Coco Chanel" },
    {quote: "Stay hungry, stay foolish.", author: "- Steve Jobs"},
    {quote: "A great man is always willing to be little.", author: "- Ralph Waldo Emerson"},
    {quote: "The greatest wealth is to live content with little.", author: "- Plato"},
    {quote: "The future belongs to those who prepare for it today.", author: "- Malcolm X"},
    {quote: "The successful warrior is the average man, with laser-like focus.", author: "- Bruce Lee"},
    {quote: "Try not to become a man of success but rather to become a man of value.", author: "- Unknown"},
    {quote: "Do what you can, with what you have, where you are.", author: "- Theodore Roosevelt"},
    {quote: "Little by little, one travels far.", author: "- J.R.R. Tolkien"},
    {quote: "I have a dream that one day little black boys and girls will be holding hands with little white boys and girls.", author: "- Unknown"},
    {quote: "Be kind whenever possible. It is always possible. ", author: "- Unknown"},
    {quote: "By failing to prepare, you are preparing to fail. ", author: "- Benjamin Franklin"},
    {quote: "I came, I saw, I conquered.", author: "- Julius Caesar"},
    {quote: "Early to bed and early to rise makes a man healthy, wealthy, and wise. ", author: "- Unknown"},
    {quote: "Nonviolence is a weapon of the strong.", author: "- Unknown"},
    {quote: "Life is either a daring adventure, or nothing.", author: "- Helen Keller"},
    {quote: "Genius is eternal patience.", author: "- Michelangelo"},
    {quote: "Not all those who wander are lost.", author: "- J.R.R. Tolkien"},
    {quote: "The root of suffering is attachment.", author: "- Unknown"}, 
    {quote: "Simplicity is the ultimate sophistication.", author: "- Leonardo da Vinci"},
    {quote: "The best way to predict your future is to create it.", author: "- Abraham Lincoln"},
    {quote: "Creativity is intelligence having fun.", author: "- Albert Einstein"},
    {quote: "I would like to die on Mars. Just not on impact.", author: "- Elon Musk"},
    {quote: "Always forgive your enemies; nothing annoys them so much.", author: "- Oscar Wilde"},
    {quote: "You laugh at me because I’m different I laugh at you because you’re all the same.", author: "- Lady Gaga"},
    {quote: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "- Unknown"},
    {quote: "I’m for truth, no matter who tells it. I’m for justice, no matter who it’s for or against.", author: "- Malcolm X"},
    {quote: "Wise men talk because they have something to say; fools, because they have to say something.", author: "- Plato"}, 
    {quote: "A wise man can learn more from a foolish question than a fool can learn from a wise answer.", author: "- Bruce Lee"}, 
    {quote: "Do not pray for easy lives, pray to be stronger men.", author:"- John F. Kennedy"}, 
    {quote: "To live happily is an inward power of the soul.", author: "- Marcus Aurelius"}, 
    {quote: "We are what we repeatedly do; excellence, then, is not an act but a habit.", author: "- Aristotle"}, 
    {quote: "If you have no critics you’ll likely have no success.", author: "- Malcolm X"}, 
    {quote: "No one has ever become poor by giving.", author: "- Anne Frank"}, 
    {quote: "A simple ‘I love you’ means more than money.", author: "- Frank Sinatra"}, 
    {quote: "A leader is a dealer in hope.", author: "- Napoleon Bonaparte"}, 
    {quote: "If you don’t like something, change it. If you can’t change it, change your attitude.", author: "- Unknown"},
    {quote: "Not everything that is faced can be changed, but nothing can be changed until it is faced.", author: "- James Baldwin"}, 
    {quote: "The highest result of education is tolerance.", author: "- Helen Keller"},  
    {quote: "Judge a man by his questions rather than his answers.", author: "- Voltaire"},
    {quote: "Hasta la vista, baby.", author: "- Terminator"},
    {quote: "Life is like a box of chocolates. You never know what you’re going to get.", author: "- Forrest Gump"}, 
    {quote: "Change will not come if we wait for some other person or some other time. We are the ones we’ve been waiting for. We are the change that we seek.", author: "- Barack Obama"},
    {quote: "It always seems impossible until it’s done.", author: "- Nelson Mandela"},
    {quote: "The unexamined life is not worth living.", author: "- Socrates"},
    {quote: "Our life is frittered away by detail… simplify, simplify.", author: "- Henry David Thoreau"},
    {quote: "The weak can never forgive. Forgiveness is the attribute of the strong.", author: "- Mahatma Gandhi"},
    {quote: "No matter who you are or what you look like, how you started off, or how and who you love, America is a place where you can write your own destiny.", author: "- Barack Obama"},
    {quote: "Turn your wounds into wisdom.", author: "- Oprah Winfrey"},
    {quote: "I don’t think of all the misery but of the beauty that still remains.", author: "- Anne Frank"},
    {quote: "Whatever you are, be a good one.", author: "- Abraham Lincoln"},
    {quote: "It’s not how much you have that makes people look up to you, it’s who you are.", author: "- Elvis Presley"},
    {quote: "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.", author: "- Bruce Lee"},
    {quote: "A man who stands for nothing will fall for anything.", author: "- Malcolm X"},
    {quote: "In order to be irreplaceable one must always be different.", author: "- Coco Chanel"},
    {quote: "You have power over your mind – not outside events. Realize this, and you will find strength.", author: "- Marcus Aurelius"},
    {quote: "Love all, trust a few, do wrong to none.", author: "- William Shakespeare"},
    {quote: "Imperfection is beauty, madness is genius and it’s better to be absolutely ridiculous than absolutely boring.", author: "- Marilyn Monroe"},
    {quote: "The path to success is to take massive, determined action.", author: "- Tony Robbins"},
    {quote: "Life is a flower of which love is the honey.", author: "- Victor Hugo"},
    {quote: "Love the life you live. Live the life you love.", author: "- Bob Marley"},
    {quote: "God helps those that help themselves.", author: "- Benjamin Franklin"},
    {quote: "I think, therefore I am.", author: "- René Descartes"},
    {quote: "To be, or not to be, that is the question.", author: "- William Shakespeare"},
    {quote: "That’s one small step for a man, one giant leap for mankind.", author: "- Neil Armstrong"},
    {quote: "The only thing that interferes with my learning is my education.", author: "- Albert Einstein"},
    {quote: "Ask not what your country can do for you, but what you can do for your country.", author: "- John F. Kennedy"},
    {quote: "The future belongs to those who believe in the beauty of their dreams.", author: "- Eleanor Roosevelt"},
    {quote: "Family is the most important thing in the world.", author: "- Diana, Princess of Wales"},
    {quote: "All I was doing was trying to get home from work.", author: "- Rosa Parks"},
    {quote: "The journey of a thousand miles begins with one step.", author: "- Lao Tzu"},
    {quote: "I’ve failed over and over and over again in my life and that is why I succeed.", author: "- Michael Jordan"},
    {quote: "Float like a butterfly, sting like a bee.", author: "- Muhammad Ali"},
    {quote: "It does not matter how slowly you go so long as you do not stop.", author: "- Confucius"},
    {quote: "Not how long, but how well you have lived is the main thing.", author: "- Seneca"},
    {quote: "It’s not whether you get knocked down, it’s whether you get up.", author: "- Vince Lombardi"},
    {quote: "You miss 100 percent of the shots you never take.", author: "- Wayne Gretzky"},
    {quote: "Peace begins with a smile.", author: "- Mother Teresa"},
    {quote: "You only live once, but if you do it right, once is enough.", author: "- Mae West"},
    {quote: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "- Henry David Thoreau"},
    {quote: "Education is the most powerful weapon which you can use to change the world.", author: "- Nelson Mandela"},
    {quote: "Good artists copy, great artists steal.", author: "- Pablo Picasso"},
    {quote: "Genius is one percent inspiration, ninety-nine percent perspiration.", author: "- Thomas A.Edison"},
    {quote: "That which does not kill us makes us stronger.", author: "- Friedrich Nietzsche"},
    {quote: "If you think you can do a thing or think you can’t do a thing, you’re right.", author: "- Henry Ford"},
    {quote: "Better to die standing than to live on your knees.", author: "- Ernesto “Che” Guevara"},
    {quote: "Big Brother is watching you.", author: "- George Orwell"},
    {quote: "Keep calm and carry on.", author: "- Winston Churchill"},
    {quote: "No.", author: "- Rosa Parks"},
    {quote: "Fear is stupid.", author: "- Marilyn Monroe"},
    {quote: "Do something worth remembering.", author: "- Elvis Presley"},
    {quote: "Elegance is refusal.", author: "- Coco Chanel"},
    {quote: "Puns are the highest form of literature.", author: "- Alfred Hitchcock"},
    {quote: "A boo is a lot louder than a cheer.", author: "- Lance Armstrong"},
    {quote: "Get busy living, or get busy dying.", author: "- Stephen King"},
    {quote: "I’m not afraid of dying, I’m afraid of not trying.", author: "- Jay-Z"},
    {quote: "Be proud of who you are.", author: "- Eminem"},
    {quote: "Better to build a bridge than a wall.", author: "- Elton John"},
    {quote: "Be the hero of your own story.", author: "- Joe Rogan"},
    {quote: "The only failure is not to try.", author: "- George Clooney"},
    {quote: "Nobody can hurt me without my permission.", author: "- Mahatma Gandhi"},
    {quote: "I am the greatest, I said that even before I knew I was.", author: "- Muhammad Ali"},
    {quote: "Don’t count the days, make the days count.", author: "- Muhammad Ali"},
    {quote: "Winners never quit, and quitters never win.", author: "- Vince Lombardi"},
    {quote: "Man – a being in search of meaning.", author: "- Plato"},
    {quote: "Well done is better than well said.", author: "- Benjamin Franklin"},
    {quote: "Believe you can and you’re halfway there.", author: "- Theodore Roosevelt"},
    {quote: "I don’t make music for eyes. I make music for ears.", author: "- Adele"},
    {quote: "We need fantasy to survive reality.", author: "- Lady Gaga"},
    {quote: "It’s fun to do the impossible.", author: "- Walt Disney"},
    {quote: "Have no fear of perfection, you’ll never reach it.", author: "- Salvador Dali"},
    {quote: "What worries you, masters you.", author: "- John Locke"},
    {quote: "There is nothing impossible to him who will try.", author: "- Alexander the Great"},
    {quote: "Whatever you do, do with all your might.", author: "- Cicero"},
    {quote: "The future starts today, not tomorrow.", author: "- Pope John Paul II"},
    {quote: "You are what you believe yourself to be.", author: "- Paulo Coelho"},
    {quote: "Stumbling is not falling.", author: "- Malcolm X"},
    {quote: "Those who dare to fail miserably can achieve greatly.", author: "- John F. Kennedy"},
    {quote: "Starting today, we must pick ourselves up, dust ourselves off, and begin again the work of remaking America.", author: "- Barack Obama"},
    {quote: "It is you, the young and fearless at heart, the most diverse and educated generation in our history, who the nation is waiting to follow.", author: "- Barack Obama"},
    {quote: "Ambition is a dream with a V8 engine.", author: "- Elvis Presley"},
    {quote: "Doing the best at this moment puts you in the best place for the next moment.", author: "- Oprah Winfrey"},
    {quote: "When our memories outweigh our dreams, it is then that we become old.", author: "- Bill Clinton"},
    {quote: "We are all of us stars, and we deserve to twinkle.", author: "- Marilyn Monroe"},
    {quote: "For beautiful eyes, look for the good in others; for beautiful lips, speak only words of kindness; and for poise, walk with the knowledge that you are never alone.", author: "- Audrey Hepburn"},
    {quote: "I am basically a feminist. I think that women can do anything they decide to do.", author: "- Grace Kelly"},
    {quote: "Do all the good you can, for all the people you can, in all the ways you can, as long as you can.", author: "- Hillary Clinton"},
    {quote: "Never doubt yourself. Never change who you are. Don’t care what people think and just go for it.", author: "- Britney Spears"},
    {quote: "Power is not given to you. You have to take it.", author: "- Beyonce"},
    {quote: "Don’t settle for what life gives you; make life better and build something.", author: "- Ashton Kutcher"},
    {quote: "Everything negative – pressure, challenges – is all an opportunity for me to rise.", author: "- Kobe Bryant"},
    {quote: "No man has a good enough memory to be a successful liar.", author: "- Abraham Lincoln"},
    {quote: "If you let your head get too big, it’ll break your neck.", author: "- Elvis Presley"},
    {quote: "Lots of people want to ride with you in the limo, but what you want is someone who will take the bus with you when the limo breaks down.", author: "- Oprah Winfrey"},
    {quote: "Propan Butaaan, Propan BUTAAAAAAN", author: "Bubbles"},
    {quote: "Jak jesteś taki mądry, to pójdź na konkurs", author: "Dominik Kurier6969 Murasicki"}
]

export default quotes;